### ISSUE TITLE
File Listing Endpoints

### ISSUE THREAD

**Issue by zhaofengli** [fzakaria/nix-http-binary-cache-api-spec#1]
First of all, thank you for doing this! Concrete documentations like this are sorely needed in the Nix ecosystem, especially for things like the binary cache API.

Binary caches often [1] expose the file listings of NARs as JSON files under `{storePathHash}.ls`. For example, the list of files of `/nix/store/p4pclmv1gyja5kzc26npqpia1qqxrf0l-ruby-2.7.3` on https://cache.nixos.org can be found at https://cache.nixos.org/p4pclmv1gyja5kzc26npqpia1qqxrf0l.ls. The compression used is indicated in the response `Content-Encoding` header (in this case, Brotli), and there does not seem to be a way to know the encoding in advance as the `.ls` files are not mentioned in the corresponding `.narinfo`s.

We cannot expect the cache to respect our `Accept-Encoding` header because for S3 caches, the compressed files are [directly uploaded](https://github.com/NixOS/nix/blob/master/src/libstore/s3-binary-cache-store.cc#L394). You can verify this behavior with the aforementioned link.

[1] https://cache.nixos.org and [S3 caches created by Nix](https://github.com/NixOS/nix/blob/2cd1a5b8f31627a09ac34afcbb0f76e90606204f/src/libstore/binary-cache-store.cc#L209) support this.

**Comment by fzakaria** [comment]
Oh interesting. Unfortunate it's such a new encoding.
Do you have insight if **/nix-cache-info** identifies whether the binary cache supports the endpoint?
It's lack of linking with the narinfo and compression seems like a miss ? 
Maybe a bug should be opened.

```bash
curl https://cache.nixos.org/p4pclmv1gyja5kzc26npqpia1qqxrf0l.ls | brotli -d | jq 

{
  "version": 1,
  "root": {
    "type": "directory",
    "entries": {
      "bin": {
        "type": "directory",
        "entries": {
          "bundle": {
            "type": "regular",
            "size": 576,
            "executable": true,
            "narOffset": 400
          },
          "bundler": {
            "type": "regular",
            "size": 578,
            "executable": true,
            "narOffset": 1192
          },
          "erb": {
            "type": "regular",
            "size": 5110,
            "executable": true,
            "narOffset": 1992
          },
          "gem": {
            "type": "regular",
            "size": 592,
            "executable": true,
            "narOffset": 7320
          },
```

**Comment by fzakaria** [comment]
@edolstra if you think an issue should be opened so that it's added to **narinfo**.

**Comment by edolstra** [comment]
Compression is handled at the HTTP level by the `content-encoding: br` header, so it's not really necessary to put it in the .narinfo. E.g `curl --compressed https://cache.nixos.org/p4pclmv1gyja5kzc26npqpia1qqxrf0l.ls | jq` works, and you can open the URL in the browser and it will be decompressed automatically. The same applies to build logs.

**Comment by fzakaria** [comment]
I was also speaking to the fact whether the path exists or not as supported
by the binary cache.
Are all binary-caches expected to have this PATH ? The earlier discussion
made it sound like only-some may.

Can you let me know of the build-log example so that I can codify it in the
spec as well?

Cheers,
Farid Zakaria

**Comment by edolstra** [comment]
Logs are stored under `log/<drv>`. For example:
```
$ nix path-info --store https://cache.nixos.org --json /nix/store/r73n0y7l5drm6w66fa3cdmlgmnss2wgq-coreutils-8.32 | jq -r .[].deriver
/nix/store/rk9xksf05l1m0rcs4n94nm8r6rvyp33s-coreutils-8.32.drv

$ curl --compressed https://cache.nixos.org/log/rk9xksf05l1m0rcs4n94nm8r6rvyp33s-coreutils-8.32.drv
...
```
